### ISSUE TITLE
Add device/instance info to requests

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/nr-assistant#16]
### Description

Currently, we have no way of knowing which type of instance is calling to the assistant service and so no means of providing tailored responses. Nor do we have the ability to pinpoint which instances an error occurs for.

This issue is requesting device/instance id and any additional info is included in the request to permit such features and future possibilities.  

Initially, this can just be via `X-` or `Vendor-` headers

```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/4160
- [x] Update PostHog reports
```

**Comment by joepavitt** [comment]
We should also update the PH node in the flow to include the `group` of the relevant `instance`

**Comment by Steve-Mcl** [comment]
verified in PostHog
